trigger:
- main

pool:
  name: Agentpool-01   # Make sure this matches exactly

variables:
  workingDirectory: $(System.DefaultWorkingDirectory)

steps:

# Install specific Terraform version (from extension)
- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: '1.6.6'

# Terraform Init
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Terraformkey'
    backendAzureRmUseEnvironmentVariablesForAuthentication: false
    workingDirectory: '$(workingDirectory)'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Terraformkey'
    workingDirectory: '$(workingDirectory)'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Terraformkey'
    workingDirectory: '$(workingDirectory)'
    args: '-auto-approve'