# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Agentpool-01

steps:
- script: terraform --version
  displayName: 'Check Terraform Version'

- script: |
    rmdir /s /q .terraform
    del terraform.lock.hcl
  displayName: 'Clean Terraform Cache'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'
